modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="alternative_mekanisms"
version="1.0.0"
displayName="Alternative Mekanisms"
displayURL="https://terjokan.de"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Terjokan, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.alternative_mekanisms]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alternative_mekanisms]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.alternative_mekanisms]]
    modId="mekanism"
    type="required"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration